# Generated by Django 4.2.8 on 2024-01-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='author_id',
            new_name='author',
        ),
    ]
